/**
 * This file was generated by the Jeddict
 */
package kbse_nkso_client.entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;

/**
 * @author nolde
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "Post.findAll", query= "SELECT s FROM Post s"),
    @NamedQuery(name = "Post.findByUrl", query= "SELECT s FROM Post s WHERE s.url= :url")
})
public class Post implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(unique = true, nullable = false)
    @Basic
    private String url;

    @Column(nullable = false)
    @Basic
    private String description;

    @Column(nullable = false)
    @Basic
    private int totalRating;

    @ManyToOne(targetEntity = SystemUser.class)
    private SystemUser author;

    @OneToMany(targetEntity = Comment.class)
    private List<Comment> comments;

    @OneToMany(targetEntity = Rating.class)
    private List<Rating> ratings;

    /**
     *
     * @return
     */
    public Long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getUrl() {
        return this.url;
    }

    /**
     *
     * @param url
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     *
     * @return
     */
    public String getDescription() {
        return this.description;
    }

    /**
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return
     */
    public int getTotalRating() {
        return this.totalRating;
    }

    /**
     *
     * @param totalRating
     */
    public void setTotalRating(int totalRating) {
        this.totalRating = totalRating;
    }

    /**
     *
     * @return
     */
    public SystemUser getAuthor() {
        return this.author;
    }

    /**
     *
     * @param author
     */
    public void setAuthor(SystemUser author) {
        this.author = author;
    }

    /**
     *
     * @return
     */
    public List<Comment> getComments() {
        if (comments == null) {
            comments = new ArrayList<>();
        }
        return this.comments;
    }

    /**
     *
     * @param comments
     */
    public void setComments(List<Comment> comments) {
        this.comments = comments;
    }

    /**
     *
     * @param comment
     */
    public void addComment(Comment comment) {
        getComments().add(comment);
        //comment.setPost(this);
    }

    /**
     *
     * @param comment
     */
    public void removeComment(Comment comment) {
        getComments().remove(comment);
        //comment.setPost(null);
    }

    /**
     *
     * @return
     */
    public List<Rating> getRatings() {
        if (ratings == null) {
            ratings = new ArrayList<>();
        }
        return this.ratings;
    }

    /**
     *
     * @param ratings
     */
    public void setRatings(List<Rating> ratings) {
        this.ratings = ratings;
    }

    /**
     *
     * @param rating
     */
    public void addRating(Rating rating) {
        getRatings().add(rating);
        //rating.setPost(this);
    }

    /**
     *
     * @param rating
     */
    public void removeRating(Rating rating) {
        getRatings().remove(rating);
        //rating.setPost(null);
    }

    /**
     *
     */
    public void calcTotalRating() {
        int res = 0;
        for (Rating rating : ratings) {
            res += rating.getRatedValue();
        }
        setTotalRating(res);
    }

}
