/**
 * This file was generated by the Jeddict
 */
package kbse_nkso_client.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author nolde
 */
@Entity
public class Rating implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private int ratedValue;

    @ManyToOne(targetEntity = SystemUser.class)
    private SystemUser user;

    
    //@ManyToOne(targetEntity = Post.class)
    //private Post post;

    /**
     *
     * @return
     */

    public Long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public int getRatedValue() {
        return this.ratedValue;
    }

    /**
     *
     * @param ratedValue
     */
    public void setRatedValue(int ratedValue) {
        this.ratedValue = ratedValue;
    }

    /**
     *
     * @return
     */
    public SystemUser getUser() {
        return this.user;
    }

    /**
     *
     * @param user
     */
    public void setUser(SystemUser user) {
        this.user = user;
    }
    /*
    public Post getPost() {
        return this.post;
    }

    public void setPost(Post post) {
        this.post = post;
    }
    */
}